pull_request_rules:
  - name: merge on CI success
    conditions:
      - status-success=Python application
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: {}
