pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Python application
      - label=merge
    actions:
      merge:
        method: squash
        strict: true
